application: parabaytest
version: 1
runtime: python
api_version: 1

default_expiration: 1s  # This is good for images, which never change

inbound_services:
- mail
- xmpp_message

handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/(script.js|styles.css|upload.py)
  static_files: static/\1
  upload: static/(script.js|styles.css|upload.py)
  expiration: 1h  # Shorter expiration, these change often

- url: /static
  static_dir: static
- url: /static/login
  static_dir: static/login
- url: /static/app
  static_dir: static/app
  
- url: /load
  script: services/bulkloader.py

# Data uploader
- url: /assets/*
  script: services/uploadservice.py
  
- url: /assetlist/*
  script: services/assetlist.py
    
- url: /_ah/mail/.+ 
  script: services/incomingemailhandler.py 
  login: admin

- url: /_ah/xmpp/message/chat/ 
  script: services/incomingxmpphandler.py 
  login: admin
      
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: .*
  script: main.py
